-- Create empty building composite table

DROP TABLE IF EXISTS dcp_buildings_composite CASCADE;
CREATE TABLE dcp_buildings_composite (
	bbl text,
	bbl_text text,
	bin text,
	doitt_id text,
    cd text,
    bldgclass text,
    landuse text,
    ownername text,
    ownertype text,
    numbldgs text,
    numfloors text,
    lotarea text,
    unitsres text,
    unitstotal text,
    bsmtcode text,
    proxcode text,
    lottype text,
    yearbuilt text,
    yearalter1 text,
    yearalter2 text,
    borocode text,
    height_roof text,
    last_status_type text,
    shape text,
    complex_type text,
    complex text,
    oem_name text,
    label text,
    pad_addr text,
    usps_addr text,
    city text,
    zip text,
    multzip text,
    mas_constrtype text,
    bctcb text,
    feature_code text,
    ground_elevation text
);
