INSERT INTO dcp_buildings_composite (
	bbl,
	bin,
	doitt_id,
        cd,
        bldgclass,
        landuse,
        ownername,
        ownertype,
        numbldgs,
        numfloors,
        lotarea,
        unitsres,
        unitstotal,
        bsmtcode,
        proxcode,
        lottype,
        yearbuilt,
        yearalter1,
        yearalter2,
        borocode,
        height_roof,
        last_status_type,
        shape,
        bctcb,
        feature_code,
        ground_elevation
)
SELECT f.mpluto_bbl AS bbl,
        f.bin AS bin,
        f.doitt_id AS doitt_id,
        p.cd AS cd,
        p.bldgclass AS bldgclass,
        p.landuse AS landuse,
        p.ownername AS ownername,
        p.ownertype AS ownertype,
        p.numbldgs AS numbldgs,
        p.numfloors AS numfloors,
        p.lotarea AS lotarea,
        p.unitsres AS unitsres,
        p.unitstotal AS unitstotal,
        p.bsmtcode AS bsmtcode,
        p.proxcode AS proxcode,
        p.lottype AS lottype,
        p.yearbuilt AS yearbuilt,
        p.yearalter1 AS yearalter1,
        p.yearalter2 AS yearalter2,
        p.borocode AS borocode,
        f.heightroof AS height_roof,
        f.lststatype AS last_status_type,
        ST_AsText(f.the_geom) AS shape,
        p.borocode || p.ct2010 || p.cb2010 as bctcb,
        f.feat_code AS feature_code,
        f.groundelev AS ground_elevation
        FROM doitt_buildingfootprints f
        LEFT JOIN dcp_pluto p
        ON f.mpluto_bbl = p.bbl
        WHERE f.bin NOT IN ('1000000', '2000000', '3000000', '4000000', '5000000')
        AND f.mpluto_bbl IS NOT NULL;